### PR TITLE
Enable CPClientEnvironment to be loaded via Metacello

### PR DESCRIPTION
**Pull request by macta**
@ErikOnBike wonder if you might consider adding this - it allows your project to pull in the CPClientEnvironment via a metacello script - so then its much easier to get started - and also makes is much easier to pull new changes to CPCE from within pharo.

e.g. you can put this in your project baseline ( you could also consider removing the "-" in CP-ClientEnvironment repo name to make it more Iceberg compatible

spec 
 	baseline: 'CodeParadise' with: [  spec 
		repository: 'github://ErikOnBike/CodeParadise/repository' ].	
spec 
 	baseline: 'CPClientEnvironment' with: [  spec 
		repository: 'github://macta/CP-ClientEnvironment' ].

### CODE REVIEW

**Comment by ErikOnBike** [comment]
Hi Tim. Thanx! I had this on my todo-list, but hadn't gotten around to implement. Nice. I will merge soon.

**Comment by ErikOnBike** [comment]
Tim,

Tiny detail: Could you rename the baseline to BaselineOfC**p**ClientEnvironment (so Cp instead of CP) to be consistent with naming convention I'm trying to follow (see also CpDomElement instead of CpDOMElement etc).

Cheers,
Erik

**Comment by macta** [comment]
I've renamed the Baseline as requested however this isn't diff'ing properly, so I'm going to look at redoing this properly in a branch

**Comment by macta** [comment]
I'm going to resubmit this as branch

**Pull request closed without merging**
