### PR TITLE
Add array support and Js user function call

### PR DESCRIPTION
**Pull request by macta**
Adds missing support for converting Smalltalk arrays to JS arrays
Adds a generic way to call a JS function with arbitrary parameters

### CODE REVIEW

**Comment by macta** [comment]
@ErikOnBike I've realised that having the ability to call arbitrary functions on dom elements is actually quite handy as well as calling global functions.

For global functions it means you can install a JS function to help you bridge some code e.g.
```
var speechSynth = new SpeechSynthesisUtterance();

function speakTextWithPitch(text,pitch) {  
	speechSynth.text = text;
	speechSynth.rate = pitch;
	window.speechSynthesis.speak(speechSynth);
};
```

For dom functions, it means you can call things like show()/hide() on a Shoelace component.

I think it has universal applicability - but obviously this can be my own private plugin now that I've worked out how to do this too. But let me know what you think.

**Comment by macta** [comment]
As a thought - you wouldn't need primitiveDomElementGlobalFunction:apply: version if we had primitiveDomElementWindow to get the window global, as then you could call primitiveDomElementFunction:apply on that object.

**Comment by ErikOnBike** [comment]
Hi Tim,

True-ish. ;-)

Why only true-ish? Window itself is not a DOM element and would therefore
not be a CpDomElement and would not have the primitive to call a JS method.

I'm thinking more of a more generic base class CpJsObject for CpDomElement
which would have the "apply function" primitive. Then a global method on
CpJsObject could be created which answer the global scope (window).

When a JS function is applied it will answer a new CpJsObject which could
be used again to apply new functions. This would be the 'bridge' I referred
to earlier. This might involve a #doesNotUnderstand: to dynamicaly call JS
methods, but I'm not sure yet. This is probably similar to what the
JsBridge plugin does (haven't looked at it recently).

The CpJsObject can then be any object within JS. Be it a Speak API
instance, a DOM element, a WebWorker thread, etc.

But I'm not 100% sure I want the JsBridge (as required element in
CpDomElement hierarchy). My purist mind keeps holding me back :-).

Cheers,
Erik

**Comment by macta** [comment]
Yes it's a tricky one to get the right balance  - it makes sense to incorporate the parameter array support into the main vm - possibly the ability to call functions on true dom objects as well.

I agree Global JS functions is where it gets trickier - as presented here, it feels a bit funny - the code should live in CpSystemPlugin - but the machinery for parameters is in the DomPlugin and it didn't feel right to have the System plugin depend on the DomPlugin to reuse that code (so I gave in and put it in DomPlugin - but I reference it from a class method on DomElement).

The trouble is - you shouldn't really need this global version - however it is handy to get you out of jail if you are really stuck - and then you can just call a global JS function.

Alternatively - might it be possibly to attach such a global function to a "pretend" Dom object - e.g. if you had a CpJSElement could you put it in your template as  <CpJsElement id='mycode' /> and then you could attach a JS function to that (rather than making it global) - and then invoking that function in a dom element would be fine?  Does this make sense - and is it possible.  This is all I need as a stepping stone - and its much simpler than having a more generic bridge object?

**Comment by ErikOnBike** [comment]
I looked at the code. You use the primitive name "primitiveDomElementFunction:apply:". I'd prefer "primitiveDomElementApply:withArguments:" in which the second argument is an array of arguments. It seems you are using this primitive (or can be using this primitive) in multiple places. It assumes there are multiple arguments in the 'original' Smalltalk method which invokes this primitive. (Remember all the arguments in the Smalltalk method will be pushed onto the stack and become available for the primitive.)

Like you would have (all primitive calls are exactly the same):
```
    MyView >> singleArgFunction: aSymbol with: anObject
        <primitive: 'primitiveDomElementFunction:apply:' module: 'CpDOMPlugin'>

    MyView >> doubleArgFunction: aSymbol with: anObject with: anotherObject
        <primitive: 'primitiveDomElementFunction:apply:' module: 'CpDOMPlugin'>

    MyView >> tripleArgFunction: aSymbol with: anObject with: anotherObject with: yetAnotherObject
        <primitive: 'primitiveDomElementFunction:apply:' module: 'CpDOMPlugin'>
```

If using "primitiveDomElementApply:withArguments:" you would simply have a single:
```
    MyView >> apply: aSymbol withArguments: anArray
        <primitive: 'primitiveDomElementApply:withArguments' module: 'CpDOMPlugin'>
```

**Comment by macta** [comment]
Your suggestion #apply:withArguments: is fair - when I first made the PR I hadn't figured out how to pass arrays - but given that I figured that bit out, we can certainly make this change.

I'll correct and resubmit.

**Comment by ErikOnBike** [comment]
Ahh..that makes sense how it came to be (ie not from some specific need).
Cool if you could update it! Thanks

**Comment by macta** [comment]
I've left in the "global" window based option - named "primitiveWindowApply:withArguments:" - but could remove that one if too controversial. I am using this one to call a Javascript function I have written to bridge the speech API. But I think it is generally applicable without having to drag in all the official JSBridge code of  SqueakJS.

Possibly you wouldn't need this primitive if there is a way to declare a JS function on a convenient Dom element? At the moment I've just written something like:

function speakTextWithPitch(text,pitch) {  
	speechSynth.text = text;
	speechSynth.rate = pitch;
	window.speechSynthesis.speak(speechSynth);
};

Which lives on the "window" global - but if I could place it on a Dom element - that would satisfy my simple needs.

**Comment by ErikOnBike** [comment]
Tim,

Since the JS squeak bundle you updated is generated from a few source files (I still have to create a repo for these) I applied the changes manually and then made a few changes. I will close this PR. You can pull the changes.

In CodeParadise (base) repo there is a method `CpDomElement >> #apply:withArguments:` to access this functionality.

I did rename `primitiveWindowApply:withArguments:` to `primitiveEnvironmentGlobalApply:withArguments:` and put it in the SystemPlugin. The CodeParadise (base) repo has a method `CpView class >> #globalApply:withArguments:` to allow using this functionality.

Thx for contributing!

**Pull request closed without merging**
